sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: dG3S0l/Dj3pkRE+GkPLdnPOiDIq6r5yt3W/xH5itIriM/JBAWBLTnWF7RD3q7xNKFmnm+B2FNs+rNxyOEqWDQc0M7saKK5aD8nQwIGldvuZoEKhHLGKMrmZ5/mpALYp6Wl4YKG3gflt/9111sALodrJOKc5Kb7ZOFwAFc4H/3iDj+5E0T/NmKyPz8h7RHcdhxzRb+SQSRa+5gLkkZOXjRtvUtnf3HG1kmE2tTRmKUK6ma+MxCUph/Xb/ljEDfe/dhw+CfmnZBS+27kx0I3YHS1TuwIm6eKewUHzJtv9z+Bgnr5sRhoQY28rHwX2yBgXJ+ipsXqWiSbdGWcIevv2o1qFVQj05xGWIP+8WF6EsmrnHQ+43fZbD97Va+6aWki8rx3AtLZtgNpgMYgiiLbuB6BZ69oy7XtTGR3s920/O61f2ivWDxwfptTHwmrJP/e2/8Z5mU84yhbl9tPfzlNHohJKWRq+7Mn/Xtd5K6gdTnz0YeQTF8F1MPdvobpiyQUkCm1ijupSVJNTS2QkRCJUImW03SbBP0/V+XxPRdb6D7ptnMZU54u50CKKbVU1rd+mMw9wwMKQG6l9gmvLwUo/LfWRvIVKxRK44O1kp9BazX/y19dXSG2zNdIZvPJMvDh7OESH8ChiIzyWplmoUiHlH16N/YlPAwA9+N2Z9pjbikrE=
  - secure: KaD7PUDOtt6I5r2SfBFJS8OF/m7RMsf72Hifzjmi/ujvxcBwoO/Jj6KVR3bX6N3WxZsd1RlW1W8PomXS/d+q3nNRu2WoaBhnWKSXUjyYjutkKQnE28BwlshLWqflvhhPfb8rtCmtjpx8DYr83emVEzkGC6IEnxqROtZJdA7Bu3Z32DQLDbaOVdnQtTcMdhZBjMPed5W3WsvRws3ZC2pqV8Q5w0b7WOMUnTIrMu5VTdbZalKC9il+7P8qt1/v4FOzzdIK60ufP+zby6GQ7zXa5yqVfEkc5xBjcEkoN3i6DByFxzvxdNQ2HsN9ENlsEmJPvoLT/Yv4rvH0P2Hfc+nT4PTEVicgzucAlSCbiOH7FTx1Wmcu4/N0XUC9Hjg+x6CdwlLfZRbd0b5bbZ77GnTA+6gx2Bk4z2AFH0Op+Mhu2xBfF5nHU1qvtjQaGRu9Opwcn3lVfdpg7VaohUOOvsS/BEHUSjYPMoW9cvmJ6b24qP82eRXShSOsEkqjFSLAydcPAduuOuL+ckGCP4i0ZbuAIFQI57NDbGcFzbbkxzDVlVph3j5xN9yNEs9d6HST2ciNOKmAQGsWCqPkVdFdtJos0JId2+WSyegkT/aVhNnyy02GuLfqVJ+mqi0SC+RPuJtC4BymrZ9vBsZVFtDvE20JJ6y+iO3WPb8A5j4yp9oWBa0=
